### Get warehouses
GRAPHQL {{baseUrl}}/graphql/

query{
  warehouse (take: 5, skip: 3, where:  {
     and: [ {
      name:  {
         contains: "Ware"
      }
      location:  {
         eq: "Rivne"
      }
     }]
  }) {
    items{
      id
      name
      location
    }
    pageInfo{
      hasNextPage
      hasPreviousPage
    }
    totalCount
  }
}

###