### Update warehouse
GRAPHQL {{baseUrl}}/graphql/

mutation{
    updateWarehouse(input:  {
       id: "b9e64da6-a122-4886-b275-88096c18cec8",
       name: "Secret Warehouse",
       location: "Vinnytsia"
    }){
    warehouse{
      name
      location
      id
    }
  }
}
###