### Sign Up
POST {{baseUrl}}/api/auth/signup
Content-Type: application/json

{
  "email": "user@example.com3",
  "phoneNumber": "809 87654321",
  "fullName": "John Doe",
  "password": "Securepassword123"
}

###