### Sign Up
POST {{baseUrl}}/api/auth/signup
Content-Type: application/json

{
  "email": "ghfgfb2bxsder34rfsdfsd@gmail.com",
  "phoneNumber": "",
  "fullName": "",
  "password": "sdasdasdsS!word123"
}

###