### Get by id warehouse from context query
GRAPHQL {{baseUrl}}/graphql/

query{
  warehouseByIdFromContext (id: "5d7dc7dc-a56f-4c4d-82a5-fa7ff4eb728d"){
    id
    name
    location
    inventories{
      productId
      productName
      quantity 
    }
  }
}

###