### Get warehouses with condition
GRAPHQL {{baseUrl}}/graphql/

query {
  warehouse(
    take: 5, 
    skip: 0, 
    where: {
      or: [
        {
          name: { contains: "Ware" }
        },
        {
          location: { eq: "Rivne" }
        }
      ]
    },
    order: [
      { name: ASC }
    ]
  ) {
    items {
      id
      name
      location
      inventories{
        productId
        productName
        quantity
      }
    }
    pageInfo {
      hasNextPage
      hasPreviousPage
    }
    totalCount
  }
}


###